feat: Show item level when pressing shift
Wynntils/Wynntils pull request #1224
Opened 2023-02-28 20:49 UTC by magicus

Also adds level extraction to several item annotators

2023-02-28 22:29 UTC, P0keDev requested changes
Binding this functionality to the shift key makes it pretty obtrusive, especially since there's no toggle for it. Ideally this should be a regular keybind that can be edited by the user; at the very least it should be changed to left control, to match the default key in legacy

2023-02-28 22:45 UTC, magicus commented
It breaks for stacking items; need to fix that first.

2023-02-28 23:52 UTC, magicus commented
We don't have any precedence of changing key bindings for when just checking if modifier keys are pressed. You have a point in that it would be nice to have this configurable, but I think it needs a bit more general rework. I changed it to control.

2023-02-28 23:55 UTC, magicus commented
It turned out we needed to disable vanilla count rendering more properly than to change the actual stack count (that one always made me squirm anyway when I saw it...).

But. There is a nice way to hook into vanilla to draw a random text instead of the stack count. The code could be made much nicer if we were to use it. But the limitation then is that the count text must be white. I started out doing the count white, but P0ke changed it so the skill point books on the compass menu gets colored. @P0keDev, would you be willing to sacrifice this? If so, we can just send in the count value to override right into the mixin, and can skip this turn on/turn off business.

2023-03-01 08:37 UTC, P0keDev commented
I'm not too sure about this new solution; if we're adding a new mixin, why not create one that allows us to cancel the item text drawing instead? That would make things much cleaner and wouldn't have the drawback of giving up color

> We don't have any precedence of changing key bindings for when just checking if modifier keys are pressed

The level overlay button is configurable in legacy (though I'm not sure if the same method would really be applicable in Artemis atm)

2023-03-01 09:57 UTC, magicus commented
> I'm not too sure about this new solution; if we're adding a new mixin, why not create one that allows us to cancel the item text drawing instead?

That is indeed what I am doing. 

Unfortunately the vanilla code is quite convoluted, and the only sane way I could find out to "cancel" the drawing is to:
1) flag in the WynnItem cache that we should cancel drawing
2) when about to draw the count in vanilla, hook in a mixin that checks this flag
3) if the flag is set, ask vanilla to draw the text "" instead
4) then draw our own text
5) and finally clear out the flag

I mean, it works. And you do get your colored texts. :-) And it does not mess with the item stack count, like the old solution. But we substituted like one line of code for a very complicated system. :-(

When I had done all this, I realized we could have instead done:
1) when about to draw the count in vanilla, hook in a mixin that sends an event
2) listen to this event, and set the count value in the event to what we want to show instead

It would have been much cleaner, and more in line with how the rest of Artemis is working. But, this is not what is proposed in this PR, since I could not find a way to change the color then. :-(

2023-03-01 10:01 UTC, magicus commented
Hm, maybe I can pull off the second solution, with color change included, after all...

2023-03-01 10:10 UTC, P0keDev commented
> > I'm not too sure about this new solution; if we're adding a new mixin, why not create one that allows us to cancel the item text drawing instead?
> 
> That is indeed what I am doing. 
> 
> Unfortunately the vanilla code is quite convoluted, and the only sane way I could find out to "cancel" the drawing is to:
> 1) flag in the WynnItem cache that we should cancel drawing
> 2) when about to draw the count in vanilla, hook in a mixin that checks this flag
> 3) if the flag is set, ask vanilla to draw the text "" instead
> 4) then draw our own text
> 5) and finally clear out the flag
> 
> I mean, it works. And you do get your colored texts. :-) And it does not mess with the item stack count, like the old solution. But we substituted like one line of code for a very complicated system. :-(
> 
> When I had done all this, I realized we could have instead done:
> 1) when about to draw the count in vanilla, hook in a mixin that sends an event
> 2) listen to this event, and set the count value in the event to what we want to show instead
> 
> It would have been much cleaner, and more in line with how the rest of Artemis is working. But, this is not what is proposed in this PR, since I could not find a way to change the color then. :-(

my suggestion is that instead of using the whole convoluted flag system, the mixin should post its own event, and then cancelling the event would stop the text from being drawn (by setting the text to an empty string, or whatever other applicable method)

2023-03-01 12:05 UTC, magicus commented
I think I got it pretty nice now. In fact, possibly almost better than before, since we now use Vanilla rendering.

2023-03-01 22:04 UTC, P0keDev submitted a review, later dismissed

2023-03-02 06:27 UTC, kristofbolyai commented on common/src/main/java/com/wynntils/mc/event/ItemCountOverlayEvent.java
> +public final class ItemCountOverlayEvent extends Event {
```suggestion
public final class ItemCountOverlayRenderEvent extends Event {
```

What do you think?

2023-03-02 06:30 UTC, kristofbolyai submitted a review, later dismissed
Otherwise LGTM. I think the @WrapOperation is a bit miss-used(, if that can even happen with a mixin :)). I can't suggest any better alternatives though, so it is fine.

2023-03-02 09:32 UTC, magicus commented on common/src/main/java/com/wynntils/mc/event/ItemCountOverlayEvent.java
> +public final class ItemCountOverlayEvent extends Event {
Sure, it's clearer.

2023-03-02 09:32 UTC, merged