fix: Fix emerald pouch's emerald displays overlapping
Wynntils/Wynntils pull request #2109
Opened 2023-09-19 18:13 UTC by Mcrtin

Removes the upper emerald display in the emerald pouch as proposed in #2087
![image](https://github.com/Wynntils/Artemis/assets/66840021/eafe3140-5e97-4d25-b523-376f6a1a4af4)
Closes #2087

2023-09-19 18:15 UTC, kristofbolyai requested changes
Not the way to fix this.. the container still has emeralds technically. Either just hide it in rendering or find a way to make it work. Text based emerald count would not work this way..

2023-09-19 19:10 UTC, Mcrtin commented
> Not the way to fix this.. the container still has emeralds technically. Either just hide it in rendering or find a way to make it work. Text based emerald count would not work this way..

I can move the upper display up until they no longer overlap. Is that a solution you'd find appropriate?

2023-09-19 19:15 UTC, DonkeyBlaster commented
What if we changed how these rendered entirely? When you have a container open, start rendering from the middle. So the stacks counter is adjacent to each other. The one for the inventory would grow downwards, going from stx>le>blocks>emeralds, and the one for the open container would grow upwards. This way we will never have overlapping counters. Thoughts?

2023-09-19 19:31 UTC, Mcrtin commented
> What if we changed how these rendered entirely? When you have a container open, start rendering from the middle. So the stacks counter is adjacent to each other. The one for the inventory would grow downwards, going from stx>le>blocks>emeralds, and the one for the open container would grow upwards. This way we will never have overlapping counters. Thoughts?

Sounds good; I've also thought about that, but it's outside the scope of this pr.

2023-09-19 20:00 UTC, Mcrtin commented
![image](https://github.com/Wynntils/Artemis/assets/66840021/8d680e56-f63a-4e52-8b95-75068b3ee602)

2023-09-20 06:30 UTC, magicus commented
The screenshot looks a bit redundant. Is the idea that if you have additional emeralds outside the pouch, that will show up in the lower half (showing the inventory), but not the upper half (showing just what is inside the pouch)?

2023-09-20 06:50 UTC, kristofbolyai approved these changes
LGTM

2023-09-20 09:59 UTC, Mcrtin commented
> The screenshot looks a bit redundant. Is the idea that if you have additional emeralds outside the pouch, that will show up in the lower half (showing the inventory), but not the upper half (showing just what is inside the pouch)?

like in every other screen, the upper display shows the emeralds in the container and the lower one shows the emeralds in the container and your pouches. In this case (which is I think the most common one for pouches), all of my emeralds are in the only pouch I have in my inv; so it basically shows the count twice. So yeah, for me its a bit redundent.

2023-09-20 19:40 UTC, magicus commented on common/src/main/java/com/wynntils/features/inventory/InventoryEmeraldCountFeature.java
> +                    int displayedTextures = (int) (Arrays.stream(getEmeraldAmounts(topEmeralds))
Is this calculating the height of the textures that renderTexturedCount() is rendering? It feels a bit complex-y, and it is not immediately clear why we should calculate it like this. I get the feeling this is based on some other code elsewhere, but there is no connection to be found.

2023-09-21 14:30 UTC, Mcrtin commented on common/src/main/java/com/wynntils/features/inventory/InventoryEmeraldCountFeature.java
> +                    int displayedTextures = (int) (Arrays.stream(getEmeraldAmounts(topEmeralds))
I've moved the conditions into the `getEmeraldAmounts` method (and renamed it). It should be clearer now where the conditions come from.

2023-09-21 20:36 UTC, magicus approved these changes
Thanks. This looks much easier to follow.

2023-09-22 16:42 UTC, merged