feat: Add additonal links to Mod Menu entry [skip ci]
Wynntils/Wynntils pull request #2819
Opened 2024-09-02 00:33 UTC by ILikePlayingGames

- Also fix fabric complaining that schemaVersion does not come first in fabric.mod.json

2024-09-02 08:13 UTC, magicus approved these changes
I guess it looks okay.

When and how does fabric complain about the schemaVersion? I've never noticed it.

2024-09-02 08:16 UTC, kristofbolyai commented
Complain is a bit strong of a word, it basically logs a warning, "schemaVersion must be the first object". Why this matters in a JSON is a mystery for me.

2024-09-02 20:23 UTC, ILikePlayingGames commented
Yeah that’s the warning I was referring to.

2024-09-02 22:05 UTC, DonkeyBlaster requested changes

2024-09-02 22:05 UTC, DonkeyBlaster commented on fabric/src/main/resources/fabric.mod.json
> +        "modmenu.discord": "https://discord.gg/wynntils-mod",
We should really use the perma invite code, in case we lose this or switch to discord.gg/wynntils again.
https://discord.gg/SZuNem8

2024-09-03 03:50 UTC, DonkeyBlaster approved these changes

2024-09-03 03:51 UTC, DonkeyBlaster commented
Also I think this is more of a `chore:`, not sure tho

2024-09-03 11:29 UTC, kristofbolyai approved these changes

2024-09-03 11:29 UTC, kristofbolyai commented
Thanks

2024-09-03 11:32 UTC, merged